version: "3.8"
services:
  web:
    build: ./kafka_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./kafka_backend:/app
      # - ./.env:/app/.env # Explicitly mount the .env file
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      - SQL_HOST=db
      - SQL_PORT=5432
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespassword
      - POSTGRES_DB=kafka
    ports:
      - "5432:5432" # Optional: expose DB port for local debugging
volumes:
  postgres_data:
