# Generated by Django 5.1.7 on 2025-04-22 19:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_property_favourited'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['country'], name='property_pr_country_45acf4_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['category'], name='property_pr_categor_29a1e2_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['price_per_night'], name='property_pr_price_p_1d4190_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['guests'], name='property_pr_guests_456e11_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['bedrooms'], name='property_pr_bedroom_6d8f3c_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['bathrooms'], name='property_pr_bathroo_ed85bd_idx'),
        ),
    ]
