# Generated by Django 5.1.7 on 2025-04-23 17:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_property_property_pr_country_45acf4_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['property', 'start_date', 'end_date'], name='property_re_propert_90ca18_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['created_by'], name='property_re_created_c4c33f_idx'),
        ),
    ]
